version: '3'

services:
  api:
    container_name: api
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: "uvicorn backend.api.app:main_api_app --host 0.0.0.0 --reload"
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    volumes:
      - ./bot:/bot
    command: 'python3 main.py'
    env_file:
      - ./.env
    depends_on:
      - api
      - redis
      - postgres

  redis:
    container_name: redis
    command: redis-server --save 30 1
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: