name: "Running project tests"
on:
  push:
    branches:
      - adding_gh_actions
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Preparing Python ${{ matrix.python-version }} for tests
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Running tests
        run: |
          cd ./tests
          python -m unittest